### ISSUE TITLE
Twilio Conversation initialization error

### ISSUE THREAD

**Issue by ianblankspace1999** [twilio/twilio-conversations-demo-android-kotlin#33]
I tried to initialize the twilio conversation but it always enter the onError state. base on the error, its said client initialisation timeout and the status code is 500.  I run it on debug state in androidStudio and all parameters passed in create function is not null but I still got this initialisation error. 

    create(getApplication(),
            chatConfig.token,
            properties,
            object : CallbackListener<ConversationsClient> {
                override fun onSuccess(client: ConversationsClient?) {
                    twilioClient = client?.also { chatClient ->
                    //some code
                    }
                }
                override fun onError(errorInfo: ErrorInfo?) {
                    errorInfo?.let { setServerError(it.message) }
                }
            }
        )

**Comment by berkus** [comment]
What is the error message? Also can you please include logs? [This is how](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md) generally bugs should be reported.

**Comment by ianblankspace1999** [comment]
![Screen Shot 2022-03-07 at 1 42 12 PM](https://user-images.githubusercontent.com/12027929/156976179-4ce6326b-cfe4-47a8-9775-c46889ced54c.png)

Hi @berkus, this is what I found in the logs.

**Comment by berkus** [comment]
No response, closing.
