### ISSUE TITLE
Invite a user to conversation like programmable Chat

### ISSUE THREAD

**Issue by DasJhaman** [twilio/twilio-conversations-demo-android-kotlin#34]
Hello is there any way to invite a user in conversation before creating one to one conversation between two users, as we had in programmable Chat I am unable to find anything in dos so I am creating an issue here?

**Comment by berkus** [comment]
Hi, no, invites are currently not supported by the Conversations product.

If you could state your intended use case I might suggest a workaround and will also raise awareness to the team about why this feature is needed.

**Comment by DasJhaman** [comment]
My intended case is that the user first invites another user when he accepts then he can send the message. This is the case let me know how can we deal with this case without having invite resources in user.

**Comment by berkus** [comment]
Conversations are more backend-heavy than the Chat product before it. It is mostly related to the fact that you operate with more different access channels (SMS, WhatsApp, etc).

The invites are quite hard to implement for SMS for example - how would you see the invite without joining the conversation first?

If you are building your product for chat users only, you could use conversations as additional signalling tools: for example, create the "userXXX_invites" conversation and send messages there whenever user is invited to a channel.

This is how it could look:

Conversation: "userXXX_invites"
Participants: userXXX (only that user)

Your backend would send a message (in pseudo-json) "invite: { from: userYYY, toConversation: CHzzzzzz }"

when user recieves this the app will:
1. parse the message
2. advance the read horizon on this conversation to mark the invite as processed
3. show the invite UI in the app
4. if the user accepts or rejects the invite, the app will write a response in this conversation like "inviteResponse: { from: userYYY, toConversation: CHzzzzz, resolution: accepted }"

The backend per-message webhook will handle this message and ADD userXXX to conversation with userYYY

**Comment by berkus** [comment]
Additional bonus here is that you could for example add an invitation message: "invite: { to: CHzzz, message: "Hi Please join my conversation" } and it's a lot more flexible.

**Comment by DasJhaman** [comment]
Could you please send me doc url

**Comment by berkus** [comment]
Which doc?

**Comment by berkus** [comment]
No response, closing.
