### ISSUE TITLE
Notifications do not trigger on message received, receiving a parsing error instead

### ISSUE THREAD

**Issue by medke** [twilio/twilio-conversations-demo-android-kotlin#42]
We're using this example implementation of the twilio conversation plugin: https://gitlab.com/twilio-flutter/conversations/-/tree/master/example/android

It's connected to a flutter interface, and we're trying to debug the issue on a native level.

# Current bug behaviour
Using the provided example app, the notifications fails to show up. We get an error instead:

`25 | Sync Subscriptions | Failed to parse incoming notification: [json.exception.out_of_range.403] key ‘event’ not found`

Everything else that exclude any other source of bugs are well tested, including the connection with Firebase and showing local notifications. 

We also connected the twilio Notify service with FCM, based on some community forums suggesting that twilio notify service is separate from chat service. We tried both with and without the notify service.

# Expected behaviour
To receive a notification on message received.

# Steps to reproduce
Download the example app, provide a `jwt token` to fetch a conversation(s), register Firebase. Finally receive a message from another account.

# Environment information
**com.twilio/conversations-android 2.0.0:** [https://search.maven.org/artifact/com.twilio/conversations-android/2.0.0/aar](https://search.maven.org/artifact/com.twilio/conversations-android/2.0.0/aar) (we're currently upgrading to 4.0.0, trying if this solves the issue)
Android SDK: 33

**project/build.gradle**
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 33

    ...etc
}


dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:30.3.2')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation "com.google.firebase:firebase-messaging:10.0.1"

}
```

# Other things we tried so far:

- create a notify service API  
- link it with a mobile push notification 
- link the mobile notification with Firebase SID
- print the token of firebase initialisation 
- register for notification
- listening to all relevant events 
- running the project on both emulators and physical devices, however, no notification is shown 

Please let us know if you need more info to check the issue, including a temporary `jwt_token` that expires in 200 minutes, and the `conversation_id`

**Comment by berkus** [comment]
> 25 | Sync Subscriptions | Failed to parse incoming notification: [json.exception.out_of_range.403] key ‘event’ not found

This is not related to the push notifications in any way and can be ignored.

**Comment by berkus** [comment]
Please collect the full trace log of the SDK and send it via Twilio Support (not here).

**Comment by berkus** [comment]
No response, closing.
