### ISSUE TITLE
accessmanager dependency maven repository

### ISSUE THREAD

**Issue by raphael-dario** [twilio/twilio-conversations-demo-android-kotlin#45]
Hello.
Not sure this is the right place to post this issue. The following dependency `com.twilio:accessmanager-android:0.1.0` seems only hosted on JCenter repository. We are working on removing this repository from our android project, since it is no longer receiving updates and recommended to be removed. Would it be possible to have it hosted on another maven repository? Or maybe it is already hosted somewhere else?

Thanks for any help.

**Comment by berkus** [comment]
This dependency is not used and must be removed.

**Comment by raphael-dario** [comment]
@berkus  thanks for your reply. in our current project, it seems we use it to handle token expiration events. are you saying we don't need to handle token expiration?

**Comment by berkus** [comment]
Yes, use the ConversationsClient's `onTokenAboutToExpire` and `onTokenExpired` events, they directly replace the functions that AccessManager provided previously.

**Comment by raphael-dario** [comment]
@berkus  thanks for your help.
