### ISSUE TITLE
How to get my conversations only fetch 20 item and load more instead of get all?

### ISSUE THREAD

**Issue by bsv-anhvo** [twilio/twilio-conversations-demo-android-kotlin#54]

**Comment by tech-ajit-mob** [comment]
Please clarify.
You want to download conversations or messages from a particular conversation.

**Comment by berkus** [comment]
@bsv-anhvo you can `conversation.getLastMessages(20)` to start with last 20 messages and then use a scroll handler to fetch more via `conversation.getMessagesBefore(topMessageIndex, 20)`.
