### ISSUE TITLE
Taking too much time to appear new messages which is received from the other user If application is quit

### ISSUE THREAD

**Issue by tech-ajit-mob** [twilio/twilio-conversations-demo-android-kotlin#55]
**Problem:**  Taking too much time to make appear new messages in the application after launching the application.

**Description:**
1. User A sent a message to User B,  User B can see the new messages in the notification drawer because we are receiving new message notifications at the client end.
2. Once User B taps on the notification first application will open because the App is not in the background nor foreground.

After opening the application we are doing some operations to connect with Twilio SDK which are given below:

> 1.   Get an Updated Access token from the App server (Optional).
> 2.   We are creating the conversation client with Twilio SDK
> 3.   Updating the FCM token to the Twilio.
> 5.  After the client synchronization, we download all the pending messages from Twilio because without synchronization we can't download any messages.
> 6. Finally, we are showing the new messages in the conversation.

The above operation takes about 3 to 4 seconds which is huge.  The user wants to see the new messages after tapping the notifications.

Just from an Improvement perspective, I am asking the question. If you require any additional details or have any suggestions please let me know.

**SDK Details**
twilio_conversation_sdk= '6.0.1'

**Comment by berkus** [comment]
This is currently as it is, we cannot commit to changes in this flow until some refactorings are finished - they are in progress now but we cannot give any timelines. Improvements are looking good so far, so once they are ready this startup time should also become better.
